### ISSUE TITLE
Wrong Picture is shown

### ISSUE THREAD

**Issue by RedEdge967** [umihico/PortfolioHub#67]
# Hello
- When I filtered the website to my country, it shows my portfolio. but it shows the wrong picture. and it shows my past portfolio. I have a new portfolio. this website is showing my [portfolio-v1](https://github.com/RedEdge967/portfolio-v1)

## Screenshot
![showing wrong picture](https://user-images.githubusercontent.com/91379432/148482249-d6ae7c6f-df12-43a8-81bc-ae9ea6b9d40d.PNG)

- It must show the below picture

![Capture45](https://user-images.githubusercontent.com/91379432/148482408-fead1ad4-98ab-4502-8cdd-9e969fcb1e97.PNG)

- And now I have a new portfolio [here](https://github.com/RedEdge967/RedEdge967.github.io)

**Comment by umihico** [comment]
@RedEdge967 
Thank you for your report!

Your second repository need a hashtag `#portfolio-website` as same as your first one has. My crawler will fetch within a few days!

I don't get yet why PortfolioHub shows still shows past image. I'll update again.

**Comment by RedEdge967** [comment]
okay thanks

**Comment by umihico** [comment]
I was digging what was wrong but now it seems just updated a few hours ago.
It look this [this](https://portfoliohub.umihi.co/?user=rededge967) currently. Is this good for you? or please change one of repositories url to `https://rededge967.github.io/portfolio-v1`. Both repository have same urls so far.

I guess the reason was job queue was too many and updates are just delayed. I doubled scraping frequency, but might still takes time to be updated.

I'm closing this issue. Instead of improving job schedule, I'll create *update button* and people can trigger whenever they want.

**Comment by RedEdge967** [comment]
Now I changed the url. It's okay to close this issue. I wanted view my new portfolio in the Portfoliohub site. Thank you for changing it.
